### ISSUE TITLE
Вывести число

### ISSUE THREAD

**Issue by mrspartak** [mrspartak/chlenix#1]
Ввод: 123
Вывод: 123

**Comment by fortuns** [comment]
// Числа. 
	//Округлить до ближайшего кратного 10
var Num = 1234.32, txt1 = " - исходное значение", txt2 = " - итоговое значение"; 
console.log(Num, txt1);
Num = Math.round(Num / 10) * 10;
console.log(Num, txt2);

**Comment by mrspartak** [comment]
`
var 123;
`

**Comment by fortuns** [comment]
`// Числа. 
	//Округлить до ближайшего кратного 10
var Num = 1234.32, txt1 = " - исходное значение", txt2 = " - итоговое значение"; 
console.log(Num, txt1);
Num = Math.round(Num / 10) * 10;
console.log(Num, txt2);
`

**Comment by mrspartak** [comment]
https://github.com/mrspartak/chlenix/blob/master/index.js

**Comment by mrspartak** [comment]
https://github.com/mrspartak/chlenix/commit/7113aa5502924e22e1d96de593e99e7518e7a178

**Comment by fortuns** [comment]
chlenix/Number/Exercise 1.js

**Comment by fortuns** [comment]
https://github.com/mrspartak/chlenix/blob/master/Number/Exercise%201.js
