### ISSUE TITLE
Создать функцию конструктор "собака". На вход кличка собаки. Собака должна уметь гавкать и возвращать свою кличку.

### ISSUE THREAD

**Issue by mrspartak** [mrspartak/chlenix#11]
Пример использования:
var myDog = new Dog('Barnie');
myDog.getName(); //Barnie
myDog.bark(); //Bark Bark!!

**Comment by fortuns** [comment]
https://github.com/mrspartak/chlenix/blob/master/Function/Exercise.11.js

**Comment by mrspartak** [comment]
Написал мелкий комментарий
https://github.com/mrspartak/chlenix/blob/master/Function/Exercise.11.js
