### ISSUE TITLE
Вернуть массив содержащий количество букв в каждом слове строки

### ISSUE THREAD

**Issue by mrspartak** [mrspartak/chlenix#13]
Ввод: Who let the dogs out?
Вывод: [3, 3, 3, 4, 4]

**Comment by fortuns** [comment]
https://github.com/mrspartak/chlenix/blob/master/Complex/Exercise.13.js

**Comment by mrspartak** [comment]
Очень плохая практика перегружать массив другим типом данных. Используй для чисел второй массив просто
