### ISSUE TITLE
Имеем 2 числовые переменные. Получить количество цыфр 1 между (> <) заданными числами.

### ISSUE THREAD

**Issue by mrspartak** [mrspartak/chlenix#14]
Ввод: 10, 22
Вывод: 11

**Comment by fortuns** [comment]
https://github.com/mrspartak/chlenix/blob/master/Complex/Exercise.14.js
Поправил как ты и говорил (сократил)

**Comment by mrspartak** [comment]
Там где можно сделать простую математическую операцию, ты вставляешь цикл и потом еще что-то в нем вычисляешь и манипулируешь строкой. Переделывай

**Comment by mrspartak** [comment]
Сойдет, у тебя третья переменная в функции не делает ничего
