### ISSUE TITLE
Имеем 2 переменные. Вывести кратно или нет одна другой

### ISSUE THREAD

**Issue by mrspartak** [mrspartak/chlenix#15]
Ввод: 100, 2
Вывод: true

Ввод: 106, 3
Вывод: false

**Comment by fortuns** [comment]
https://github.com/mrspartak/chlenix/blob/master/Number/Exercise15.js

**Comment by mrspartak** [comment]
немного комментов
https://github.com/mrspartak/chlenix/blob/master/Number/Exercise15.js

**Comment by fortuns** [comment]
Посмотрел изучил:) Спасибо
