### ISSUE TITLE
Имеем 2 числа, посчитать количество целых чисел между ними

### ISSUE THREAD

**Issue by mrspartak** [mrspartak/chlenix#17]
Ввод: 1.4, 5
Вывод: 3

**Comment by fortuns** [comment]
https://github.com/mrspartak/chlenix/blob/master/Number/Exercise17.js

**Comment by mrspartak** [comment]
Если подставить в твой код 1 и 2, то выдаст неверный результат. Проверяй на разных входных данных свой код

**Comment by fortuns** [comment]
[не туда скобки воткнул:(](https://github.com/mrspartak/chlenix/blob/master/Number/Exercise17.js)

**Comment by fortuns** [comment]
https://github.com/mrspartak/chlenix/blob/master/Number/Exercise17%2B.js
вроде все работает

**Comment by mrspartak** [comment]
Советую позже вернуться к этой задаче и придумать более элегантное решение и более простое
https://github.com/mrspartak/chlenix/blob/master/Number/Exercise17+.js
