### ISSUE TITLE
Решить проблему чисел с плавающей точкой. Если ты прибавишь 0.1 + 0.2 например, то вероятнее всего получишь что-то вроде 0.30000000000000004

### ISSUE THREAD

**Issue by mrspartak** [mrspartak/chlenix#19]
Ввод: 0.1 + 0.2
Вывод: 0.3

**Comment by fortuns** [comment]
https://github.com/mrspartak/chlenix/blob/master/Number/Exercise19.js

**Comment by mrspartak** [comment]
Умничка. Целые числа кроме очень больших возвращают правильные математические результаты!
