### ISSUE TITLE
Округлить число до ближайшего кратного 10

### ISSUE THREAD

**Issue by mrspartak** [mrspartak/chlenix#2]
Ввод: 1234.32
Вывод: 1230

**Comment by fortuns** [comment]
https://github.com/mrspartak/chlenix/blob/master/Number/Exercise%201.js

**Comment by mrspartak** [comment]
Хорошо. Закоммитил комменты по задачке.
https://github.com/mrspartak/chlenix/blob/master/Number/Exercise%201.js

**Comment by fortuns** [comment]
Понял. Ок
