### ISSUE TITLE
Превратить строку, где слова разделены нижним подчеркиванием в Camel Case.

### ISSUE THREAD

**Issue by mrspartak** [mrspartak/chlenix#20]
Ввод: iam_dog_tail
Вывод: iamDogTail

**Comment by fortuns** [comment]
https://github.com/mrspartak/chlenix/blob/master/String/Exercise20.js

**Comment by mrspartak** [comment]
На строке 'iam_dog_tail_' не работает.

**Comment by fortuns** [comment]
https://github.com/mrspartak/chlenix/blob/master/String/Exercise20.js
