### ISSUE TITLE
Есть массив чисел. Определить среднее значение и среднеквадратичное отклонение.

### ISSUE THREAD

**Issue by mrspartak** [mrspartak/chlenix#21]
Ввод: [1, 1, 1, 1]
Вывод: 1, 0

**Comment by fortuns** [comment]
@mrspartak 
https://github.com/mrspartak/chlenix/blob/master/Array/Exercise.21.js

**Comment by mrspartak** [comment]
Отлично, теперь напиши прототиты объекта Array для вычисления среднего и среднеквадратичного.
Если в массиве есть нечисловые значения: выбросить ошибку. (посмотри объект Error)
Пример:
var array = [1, 2, 3];
var average = array.average();
var dev = array.deviation();

**Comment by fortuns** [comment]
https://github.com/mrspartak/chlenix/blob/master/Array/Exercise.21.2.js

**Comment by mrspartak** [comment]
Написал замечания https://github.com/mrspartak/chlenix/blob/master/Array/Exercise.21.2.js
