### ISSUE TITLE
Написать объект, который бы помог решить некоторые задачки по строкам.

### ISSUE THREAD

**Issue by mrspartak** [mrspartak/chlenix#22]
Пример.
StringHelper.toCamel('not_camel');
//notCamel
StringHelper.revert('not_camel');
//lemac_ton

**Comment by fortuns** [comment]
Получает в данном случае я создаю объект, полями которого (toCamel и revert) являются не числа/строки/булевы, а функции?
Revert - обращение строки?

**Comment by mrspartak** [comment]
toCamel и revert это методы объекта
>Revert - обращение строки?
да

**Comment by fortuns** [comment]
@mrspartak 
https://github.com/mrspartak/chlenix/blob/master/Object/Exercise.22.js

**Comment by mrspartak** [comment]
Воу. Делая вот так Object.prototype.toCamel ты теперь вообще всем объектам в JS выдал метод toCamel. Не надо так

**Comment by fortuns** [comment]
https://github.com/mrspartak/chlenix/blob/master/Object/Exercise.22.js

@mrspartak похоже я понял, что ты хотел увидеть

**Comment by mrspartak** [comment]
Первая часть с String.prototype полная фигня. Так можно делать, но не так, как сделал ты. String - глобальный текстовый объект. Он содержит текстовую переменную, это значит, что у любого текста будет твой метод, но в него ты зачем-то должен передавать текст.
var text = '123';
text.toCamel('123') ?? 
В таком случае уж пиши, чтобы использовался текущий текст и это работало как
var text = '123';
text.toCamel();

Второй вариант я и хотел увидеть. У тебя 2 типа объектов в JS: конструкторы и обычные. Обычные свои методы хранят только в себе, конструкторы методы наследуют от прототипа.

**Comment by mrspartak** [comment]
Насчет камелкейса это интересная задачка, т.к. она решается миллионом способов. Погляди решения тут, попробуй понять некоторые
http://stackoverflow.com/questions/2970525/converting-any-string-into-camel-case
