### ISSUE TITLE
Написать рекурсивную функции чисел фибоначи. Это сложная задачка.

### ISSUE THREAD

**Issue by mrspartak** [mrspartak/chlenix#24]
fib(3);
//на вход принимает количество чисел и выводит их
//1 1 2

**Comment by fortuns** [comment]
https://github.com/mrspartak/chlenix/blob/master/Function/Exercise.24.note.js
работающая версия, но чуть позже  напишу красивее

**Comment by fortuns** [comment]
https://github.com/mrspartak/chlenix/blob/master/Function/Exercise.24.note.js

**Comment by fortuns** [comment]
https://github.com/mrspartak/chlenix/blob/master/Function/Exercise.24.note.js

**Comment by mrspartak** [comment]
Кстати, насчет точности ) Я ошибся в примере, ты не ошибся с выводом, но ошибся с условием.
Мы задаем на входе количество чисел фибоначи, ты выводишь на 1 больше =)

Ну а по факту задачу ты не смог решить. Я уже делал замечание про использование чисел с плавающей точкой, ты подумал, что округлением ее решил, но уже с 76 значения ты получаешь не те числа. Там где можно решать целыми числами, НУЖНО решать все в целых числах.
https://i.gyazo.com/a54a53e7e5938f3e6cd38453cd24fc7c.png

Также изначально задача ставилась решить это дело рекурсией, дабы понять как работает рекурсия заоодно

**Comment by mrspartak** [comment]
Погляди
https://github.com/mrspartak/chlenix/blob/master/Function/Exercise.24.sp.js

**Comment by mrspartak** [comment]
Добавил комменты и убрал лишнее условие
https://github.com/mrspartak/chlenix/blob/master/Function/Exercise.24.sp.js
