### ISSUE TITLE
Написать простенький шаблонизатор. Любое слово в строке между символами {example} будет заменятся на значение в объекте с ключем example

### ISSUE THREAD

**Issue by mrspartak** [mrspartak/chlenix#27]
Ввод: str = 'Hi {name}.', obj = {name: 'Pavel'}
Вывод: Hi Pavel.

**Comment by fortuns** [comment]
https://github.com/mrspartak/chlenix/blob/master/Complex/Exercise.27.js

@mrspartak это предварительный вариант. 
В каком виде ты хотел бы задавать "example"?

**Comment by fortuns** [comment]
доработать с учетом объекта любого вида

**Comment by fortuns** [comment]
@mrspartak 
https://github.com/mrspartak/chlenix/blob/master/Complex/Exercise.27.js

**Comment by mrspartak** [comment]
не работает, если объект содержит больше одного ключа

**Comment by fortuns** [comment]
@mrspartak 
fixed
https://github.com/mrspartak/chlenix/blob/master/Complex/Exercise.27.js

**Comment by mrspartak** [comment]
Сойдет и все же мог сделать наоборот, обойти переменные, а не строку, ну да ладно.
Почитай про простой шаблонизатор, который при этом может еще траверсить объект и ставить например условия прям в шаблоне
http://krasimirtsonev.com/blog/article/Javascript-template-engine-in-just-20-line
Пример клиентского "профессионального" шаблонизатора
https://www.jsviews.com/#jsr-quickstart
