### ISSUE TITLE
Дана длина 3х сторон треугольника. Вернуть тип трейгольника: не существует, остроугольный, тупоугольный, прямоугольный

### ISSUE THREAD

**Issue by mrspartak** [mrspartak/chlenix#28]
Ввод: 1, 2, 3
Вывод: Не существует

**Comment by fortuns** [comment]
https://github.com/mrspartak/chlenix/blob/master/Complex/Exercise.28.js

**Comment by mrspartak** [comment]
Написал мелкие комменты, все ок.
https://github.com/mrspartak/chlenix/blob/master/Complex/Exercise.28.js
