### ISSUE TITLE
Глобальные объекты

### ISSUE THREAD

**Issue by mrspartak** [mrspartak/chlenix#29]
Ознакомится с глобальными объектами
window
document

Получить при помощи них
1. Размерности текущего браузерного окна ширину, высоту.
Окон несколько, это весь браузер и окно самого сайта, получить нужно всех.

2. Запросить у юзера его возраст и вывести в html и в диалоговом окне alert сколько ему будет через 5 лет.

3. Вывести данные о текущей ссылке сайта со всеми параметрами

4. Вывести в консоль, как много на странице блоков div

**Comment by fortuns** [comment]
https://github.com/mrspartak/chlenix/blob/master/BrowserJS/Exercise29/Exercise.29.js

**Comment by mrspartak** [comment]
все гуд. Советую собирать "помощников" у себя. Например для валидации ввода пользователя. Вот ты ожидаешь число, но никак не проверяешь это. В этой задаче это не важно, но можно написать пару функций и юзать их везде в своем коде
