### ISSUE TITLE
Имеем 2 переменные, строку и букву. Вернуть количество вхождений буквы в строке.

### ISSUE THREAD

**Issue by mrspartak** [mrspartak/chlenix#3]
Ввод: 'What a wonderfull world', 'w'
Вывод: 3

**Comment by fortuns** [comment]
https://github.com/mrspartak/chlenix/blob/master/String/Exercise3.js

**Comment by mrspartak** [comment]
Попробуй еще решить эту задачку с помощью метода объекта типа string indexOf

**Comment by fortuns** [comment]
https://github.com/mrspartak/chlenix/blob/master/String/Excercise3%2B.js
