### ISSUE TITLE
Обратить строку

### ISSUE THREAD

**Issue by mrspartak** [mrspartak/chlenix#4]
Ввод: what the fuck
Вывод: kcuf eht tahw

**Comment by fortuns** [comment]
В этом задании учитываем что пробелы в исходной строке могут стоять незеркально?

**Comment by mrspartak** [comment]
Вообще полностью все строку перевернуть. Пробел тоже символ

**Comment by fortuns** [comment]
https://github.com/mrspartak/chlenix/blob/master/String/Exercise4.js

**Comment by mrspartak** [comment]
Комментики
https://github.com/mrspartak/chlenix/blob/master/String/Exercise4.js
