### ISSUE TITLE
Заменить каждый второй символ в строке на 0.

### ISSUE THREAD

**Issue by mrspartak** [mrspartak/chlenix#5]
Ввод: ciu33cb23093jch3
Вывод: c0u030b03090j0h0

**Comment by fortuns** [comment]
https://github.com/mrspartak/chlenix/blob/master/String/Exercise5.js

**Comment by mrspartak** [comment]
Комментики
https://github.com/mrspartak/chlenix/blob/master/String/Exercise5.js
