### ISSUE TITLE
Вывести максимальный и минимальный числовой элемент массива

### ISSUE THREAD

**Issue by mrspartak** [mrspartak/chlenix#7]
Ввод: [2, 4, true, 'efwef', 2, 4, 6, {a: 123}]
Вывод: 2, 6

**Comment by fortuns** [comment]
@mrspartak look at this
https://github.com/mrspartak/chlenix/blob/master/Array/Exercise7.js

**Comment by mrspartak** [comment]
@fortuns комменты и код не работает на некоторых массивах. Переписывай
https://github.com/mrspartak/chlenix/blob/master/Array/Exercise7.js

**Comment by fortuns** [comment]
@mrspartak 
https://github.com/mrspartak/chlenix/blob/master/Array/Exercise7.2.js

**Comment by mrspartak** [comment]
Все еще не работает на некоторых массивах. Чини

**Comment by fortuns** [comment]
https://github.com/mrspartak/chlenix/blob/master/Array/Exercise7.2.js

**Comment by mrspartak** [comment]
`if (i1 == myArray[(myArray.length-1)]) {
	marker = 1;
}`
Что это? индекс равен последнему элементу массива? поделись чем курил.
Решение принимаю, но все же реальное решение делается в один цикл
